'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Task31

	'''<summary>
	'''rdlMagazine control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rdlMagazine As Global.System.Web.UI.WebControls.RadioButton

	'''<summary>
	'''rdlTelevision control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rdlTelevision As Global.System.Web.UI.WebControls.RadioButton

	'''<summary>
	'''rdlOther control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rdlOther As Global.System.Web.UI.WebControls.RadioButton

	'''<summary>
	'''lblResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label
End Class
