'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminHome

	'''<summary>
	'''LabelWelcome control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelWelcome As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTotalStudent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalStudent As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelUnfreezeStudent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelUnfreezeStudent As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelFreezeStudent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelFreezeStudent As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTotalTutor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalTutor As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelUnfreezeTutor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelUnfreezeTutor As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelFreezeTutor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelFreezeTutor As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTotalCourse control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalCourse As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTotalCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalCategory As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTotalMaterial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalMaterial As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelnoCourses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelnoCourses As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoTutors control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoTutors As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoStudents control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoStudents As Global.System.Web.UI.WebControls.Label
End Class
