'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminCRUDMaterialType

	'''<summary>
	'''gvs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvs As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''updatePanelTop1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updatePanelTop1 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''LabelAddMaterialName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelAddMaterialName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TextBoxAddMaterial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxAddMaterial As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''AddButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AddButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''updatePanelTop2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updatePanelTop2 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''LabelUpdateMaterialName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelUpdateMaterialName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''myHiddenId control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents myHiddenId As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''TextBoxUpdateMaterial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxUpdateMaterial As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''UpdateButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdateButton As Global.System.Web.UI.WebControls.Button
End Class
