'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HOLogin

  '''<summary>
  '''TextBoxUsernameTutorLog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxUsernameTutorLog As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TextBoxPasswordTutorLog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxPasswordTutorLog As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TutorRememberMe control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TutorRememberMe As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ButtonTutorLogin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonTutorLogin As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''LabelReset control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelReset As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblStatus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
End Class
