'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HORateHK

  '''<summary>
  '''LabelHKName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelHKName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''textBoxPhoneNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents textBoxPhoneNumber As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''REVPhonenumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents REVPhonenumber As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''ButtonRate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonRate As Global.System.Web.UI.WebControls.Button
End Class
