'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HOViewsListOfHK

  '''<summary>
  '''LabelTotalStudent control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTotalStudent As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelTotalStudentPending control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTotalStudentPending As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelTotalStudentRejected control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTotalStudentRejected As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''gvs control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gvs As Global.System.Web.UI.WebControls.GridView
End Class
