'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HOViewHKinJob

  '''<summary>
  '''Labelcoursename control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Labelcoursename As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''UpdatePanel1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''ddlCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txtSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Repeater1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater
End Class
