'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HOViewHKProfile

  '''<summary>
  '''LabelTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Image1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''LabelUserName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelUserName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelFirstName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelLastName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelBirthDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelBirthDate As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelPhoneNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelPhoneNumber As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelEmail As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''CheckBoxFreeze control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CheckBoxFreeze As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''LinkButtonBack control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LinkButtonBack As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''ButtonAccept control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonAccept As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''ButtonRejected control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonRejected As Global.System.Web.UI.WebControls.LinkButton
End Class
