'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateJob

  '''<summary>
  '''HiddenFieldCourseId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenFieldCourseId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''HiddenFieldTutorId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenFieldTutorId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''TextBoxCourseName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxCourseName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''CheckBoxListCourseCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CheckBoxListCourseCategory As Global.System.Web.UI.WebControls.CheckBoxList

  '''<summary>
  '''Label1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TextBoxScheduleDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxScheduleDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TextBoxCreatedDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxCreatedDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TextBoxCourseDescription control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxCourseDescription As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TextBoxsalary control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxsalary As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ddl0 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddl0 As Global.System.Web.UI.HtmlControls.HtmlSelect

  '''<summary>
  '''SendA control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SendA As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''CheckBoxvacant control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CheckBoxvacant As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''btnview control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnview As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''btnUpdate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
End Class
