'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewJob1

  '''<summary>
  '''HiddenFieldCourseId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenFieldCourseId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''HiddenFieldTutorId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenFieldTutorId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''LabelTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCourseName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCourseName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''CheckBoxvacant control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CheckBoxvacant As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''LabelDescription control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDescription As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatedead control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatedead As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelLocation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelLocation As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategoryName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategoryName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btUpdate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
