'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class task16

	'''<summary>
	'''textBoxFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxFirstName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''requiredFieldVallidatorFirstname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents requiredFieldVallidatorFirstname As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''textBoxSurName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxSurName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''requiredFieldVallidatorSurname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents requiredFieldVallidatorSurname As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''textBoxUserName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxUserName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''requiredFieldVallidatorUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents requiredFieldVallidatorUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''RFVPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RFVPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''REVPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents REVPassword As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''txtConfirmPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CVConfirmPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CVConfirmPassword As Global.System.Web.UI.WebControls.CompareValidator

	'''<summary>
	'''textBoxEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''RequiredFieldValidator5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''textBoxPhoneNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxPhoneNumber As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''textBoxZipCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxZipCode As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddCountry control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddCountry As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''CVCountryDropDown control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CVCountryDropDown As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
