'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class task42

	'''<summary>
	'''lblCurrentBid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCurrentBid As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtYourBid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtYourBid As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CVBidCheck control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CVBidCheck As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''btnSubmitBid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmitBid As Global.System.Web.UI.WebControls.Button
End Class
