'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StudentViewsEvents

	'''<summary>
	'''HiddenFieldCourseId control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldCourseId As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''HiddenFieldTutorId control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldTutorId As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''gvs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvs As Global.System.Web.UI.WebControls.GridView
End Class
