'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminLogin

  '''<summary>
  '''TextBoxUsernameAdminLog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxUsernameAdminLog As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TextBoxPasswordAdminLog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxPasswordAdminLog As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''AdminRememberMe control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdminRememberMe As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ButtonAdminLogin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonAdminLogin As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lblStatus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
End Class
