'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SettingFocusAndUsingAutoCompleteWithTheTextBoxControl

	'''<summary>
	'''lblFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblLastname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLastname As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
