'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminViewsListOfTutorsStudents

	'''<summary>
	'''LabelTotalTutorUnfreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalTutorUnfreeze As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataListTutorUnfreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataListTutorUnfreeze As Global.System.Web.UI.WebControls.DataList

	'''<summary>
	'''LabelTotalStudentUnfreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalStudentUnfreeze As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataListStudentUnfreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataListStudentUnfreeze As Global.System.Web.UI.WebControls.DataList

	'''<summary>
	'''LabelTotalTutorFreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalTutorFreeze As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataListTutorFreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataListTutorFreeze As Global.System.Web.UI.WebControls.DataList

	'''<summary>
	'''LabelTotalStudentFreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTotalStudentFreeze As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataListStudentFreeze control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataListStudentFreeze As Global.System.Web.UI.WebControls.DataList

	'''<summary>
	'''LabelNoStudents control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoStudents As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoCourses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoCourses As Global.System.Web.UI.WebControls.Label
End Class
