'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

	'''<summary>
	'''LabelnoCourses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelnoCourses As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoTutors control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoTutors As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoStudents control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoStudents As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseTitle1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseTitle1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTutorName1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTutorName1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelDateSchedule1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelDateSchedule1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseDescription1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseDescription1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseTitle2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseTitle2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTutorName2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTutorName2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelDateSchedule2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelDateSchedule2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseDescription2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseDescription2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseTitle3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseTitle3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTutorName3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTutorName3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelDateSchedule3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelDateSchedule3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseDescription3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseDescription3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseTitle4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseTitle4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTutorName4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTutorName4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelDateSchedule4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelDateSchedule4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelCourseDescription4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelCourseDescription4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''AdRotator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator1 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator2 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator3 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator4 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator5 As Global.System.Web.UI.WebControls.AdRotator
End Class
