'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

	'''<summary>
	'''LabelnoCourses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelnoCourses As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoTutors control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoTutors As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelNoStudents control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelNoStudents As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''AdRotator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator1 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator2 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator3 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator4 As Global.System.Web.UI.WebControls.AdRotator

	'''<summary>
	'''AdRotator5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdRotator5 As Global.System.Web.UI.WebControls.AdRotator
End Class
