'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class master1

	'''<summary>
	'''headPlaceHolder1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents headPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''myform control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents myform As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ContentPlaceHolder1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''TextBoxUsernameStudentLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxUsernameStudentLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxPasswordStudentLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxPasswordStudentLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ButtonStudentLogin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ButtonStudentLogin As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''StudentRememberMe control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents StudentRememberMe As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''TextBoxUsernameTutorLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxUsernameTutorLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxPasswordTutorLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxPasswordTutorLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ButtonTutorLogin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ButtonTutorLogin As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''TutorRememberMe control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TutorRememberMe As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''TextBoxUsernameAdminLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxUsernameAdminLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxPasswordAdminLog control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxPasswordAdminLog As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ButtonAdminLogin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ButtonAdminLogin As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''AdminRememberMe control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AdminRememberMe As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''lblStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''scriptPlaceHolder1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents scriptPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
