'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddCourse

	'''<summary>
	'''HiddenFieldDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldDate As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''TextBoxCourseName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxCourseName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CheckBoxListCourseCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBoxListCourseCategory As Global.System.Web.UI.WebControls.CheckBoxList

	'''<summary>
	'''TextBoxScheduleDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxScheduleDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxCourseDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxCourseDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxAimsAndObjectives control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxAimsAndObjectives As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''FileUploadDoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FileUploadDoc As Global.System.Web.UI.WebControls.FileUpload

	'''<summary>
	'''DropDownListMaterialName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DropDownListMaterialName As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnAddMaterials control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddMaterials As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LinkButtonAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LinkButtonAdd As Global.System.Web.UI.WebControls.LinkButton
End Class
