'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddCourse

	'''<summary>
	'''HiddenFieldDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldDate As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''TextBoxCourseName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxCourseName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CheckBoxListCourseCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CheckBoxListCourseCategory As Global.System.Web.UI.WebControls.CheckBoxList

	'''<summary>
	'''cvmodulelist control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvmodulelist As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''TextBoxScheduleDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxScheduleDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxCourseDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxCourseDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxAimsAndObjectives control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxAimsAndObjectives As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''file0 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents file0 As Global.System.Web.UI.HtmlControls.HtmlInputFile

	'''<summary>
	'''ddl0 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddl0 As Global.System.Web.UI.HtmlControls.HtmlSelect

	'''<summary>
	'''SendA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SendA As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LinkButtonAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LinkButtonAdd As Global.System.Web.UI.WebControls.LinkButton
End Class
