'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TutorUpdateProfile

	'''<summary>
	'''ImageTutorProfile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ImageTutorProfile As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''HiddenFieldCourseId control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldCourseId As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''HiddenFieldTutorId control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HiddenFieldTutorId As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''TextBoxFirstnameReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxFirstnameReg As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxLastnameReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxLastnameReg As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxUsernameReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxUsernameReg As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''RegularExpressionValidatorUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RegularExpressionValidatorUsername As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''TextBoxPasswordReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxPasswordReg As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''REVPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents REVPassword As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''TextBoxConfirmReg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxConfirmReg As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''CVConfirmPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CVConfirmPassword As Global.System.Web.UI.WebControls.CompareValidator

	'''<summary>
	'''TextBoxAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TextBoxEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TextBoxEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''RFVEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RFVEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''textBoxPhoneNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxPhoneNumber As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''REVPhonenumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents REVPhonenumber As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''textBoxDOB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBoxDOB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''FileUpload1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

	'''<summary>
	'''ButtonRegister control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ButtonRegister As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lblStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
End Class
