'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index

  '''<summary>
  '''AdRotator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdRotator1 As Global.System.Web.UI.WebControls.AdRotator

  '''<summary>
  '''AdRotator2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdRotator2 As Global.System.Web.UI.WebControls.AdRotator

  '''<summary>
  '''AdRotator3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdRotator3 As Global.System.Web.UI.WebControls.AdRotator

  '''<summary>
  '''AdRotator4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdRotator4 As Global.System.Web.UI.WebControls.AdRotator

  '''<summary>
  '''AdRotator5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AdRotator5 As Global.System.Web.UI.WebControls.AdRotator

  '''<summary>
  '''LabelJobTitle1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobTitle1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobLocation1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobLocation1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategory1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategory1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobTitle2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobTitle2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobLocation2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobLocation2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategory2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategory2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobTitle3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobTitle3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobLocation3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobLocation3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategory3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategory3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobTitle4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobTitle4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobLocation4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobLocation4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategory4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategory4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobTitle5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobTitle5 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelJobLocation5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelJobLocation5 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDatePosted5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDatePosted5 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelCategory5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelCategory5 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelSalary5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelSalary5 As Global.System.Web.UI.WebControls.Label
End Class
