'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage

  '''<summary>
  '''head control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''myform control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents myform As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager2 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''pnlmanage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlmanage As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lgregis control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lgregis As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''btnlogout control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnlogout As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''guestlinknav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents guestlinknav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''Adminlinknav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Adminlinknav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''studentlinknav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents studentlinknav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''tutorlinknav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents tutorlinknav As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ContentPlaceHolder1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''ScriptPlaceHolder1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
