'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HKViewProfile

  '''<summary>
  '''LabelRating control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelRating As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelTutorName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTutorName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ImageTutorProfile control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ImageTutorProfile As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''HiddenFieldTutorId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenFieldTutorId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''LabelTutorUserName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTutorUserName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelTutorFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTutorFirstName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelTutorLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelTutorLastName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelDOB As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelAddress As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelPhone As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LabelEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelEmail As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''gvs control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gvs As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''TextBoxCert control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TextBoxCert As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ButtonAddCert control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ButtonAddCert As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btUpdate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
